services:
  app-base:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["make", "test"]

  app:
    extends:
      service: app-base
    image: an0de/devops-for-developers-project-74
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgsql:/var/lib/postgresql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgsql:
