services:
  app:
    extends:
      file: docker-compose.yml
      service: app-base
    build:
      context: .
      dockerfile: Dockerfile
    command: make dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - $PWD/app:/app:Z
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy
    volumes:
      - $PWD/services/caddy:/etc/caddy:Z
      - caddy_data:/data:Z
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - app

volumes:
  caddy_data:
